# версия docker-compose
version: '3.8'

# имя директории для хранения данных
volumes:
  postgres_data:
  static_volume:

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:latest
    # volume и связанная с ним директория в контейнере
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # адрес файла, где хранятся переменные окружения
    env_file:
      - api_yamdb/.env
  web:
    build: .
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    # "зависит от",
    depends_on:
      - db
    env_file:
      - api_yamdb/.env
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/static
    ports:
      - 1337:80
    depends_on:
      - web
